In [91]:
import ast
import numpy as np

In [25]:
import pandas as pd

df = pd.read_csv("battles-012021.csv", sep=",")
# shows top 10 rows
df.head(10)

,Unnamed: 0,battleTime,arena.id,gameMode.id,average.startingTrophies,winner.tag,winner.startingTrophies,winner.trophyChange,winner.crowns,winner.kingTowerHitPoints,...,loser.cards.list,loser.totalcard.level,loser.troop.count,loser.structure.count,loser.spell.count,loser.common.count,loser.rare.count,loser.epic.count,loser.legendary.count,loser.elixir.average
0,0,2020-12-31 21:02:12+00:00,54000050.0,72000006.0,5363.0,#PVLPJP2Y,5372.0,28.0,2.0,4145.0,...,"[26000000, 26000015, 26000023, 27000004, 28000...",104,3,1,4,1,1,4,2,3.500
1,1,2020-12-31 21:02:15+00:00,54000050.0,72000006.0,5407.0,#8PRLRYYCV,5409.0,29.0,1.0,5304.0,...,"[26000023, 26000027, 26000037, 26000046, 26000...",104,6,1,1,0,1,2,5,4.250
2,2,2020-12-31 21:02:45+00:00,54000050.0,72000006.0,5741.0,#2G8LQRCG,5749.0,28.0,2.0,5762.0,...,"[26000022, 26000027, 26000028, 26000041, 26000...",104,7,0,1,4,2,1,1,4.125
3,3,2020-12-31 21:03:13+00:00,54000050.0,72000006.0,4307.0,#Y9QL09VGV,4316.0,28.0,2.0,4392.0,...,"[26000012, 26000027, 26000031, 26000033, 26000...",80,6,1,1,2,1,2,3,3.750
4,4,2020-12-31 21:03:17+00:00,54000050.0,72000006.0,5776.5,#9RRYG9P9U,5783.0,28.0,3.0,5832.0,...,"[26000010, 26000011, 26000021, 26000037, 26000...",104,5,1,2,2,4,0,2,3.250
5,5,2020-12-31 21:03:27+00:00,54000050.0,72000006.0,4824.0,#9JVCRG9J2,4828.0,29.0,1.0,5832.0,...,"[26000001, 26000009, 26000038, 26000039, 26000...",101,5,0,3,2,3,3,0,3.625
6,6,2020-12-31 21:03:48+00:00,54000050.0,72000006.0,5125.0,#2J209CGCL,5123.0,30.0,2.0,5344.0,...,"[26000000, 26000005, 26000011, 26000031, 26000...",104,5,1,2,3,3,1,1,3.125
7,7,2020-12-31 21:03:48+00:00,54000050.0,72000006.0,5318.0,#2VUYRR2QY,5299.0,33.0,2.0,5832.0,...,"[26000004, 26000006, 26000013, 26000035, 26000...",103,6,0,2,2,2,3,1,4.000
8,8,2020-12-31 21:04:12+00:00,54000050.0,72000006.0,4679.5,#LYCQ2JGLC,4687.0,28.0,1.0,5234.0,...,"[26000000, 26000011, 26000042, 26000055, 26000...",96,5,1,2,4,1,1,2,4.250
9,9,2020-12-31 21:04:37+00:00,54000050.0,72000006.0,5169.5,#2RR29VV20,5169.0,30.0,1.0,5832.0,...,"[26000004, 26000007, 26000011, 26000017, 26000...",104,5,1,2,1,4,3,0,4.250

In [26]:
df = df.drop(columns=['Unnamed: 0', 'battleTime', 'arena.id', 'winner.tag', 'winner.startingTrophies',
       'winner.trophyChange', 'winner.crowns', 'winner.kingTowerHitPoints',
       'winner.princessTowersHitPoints', 'winner.clan.tag',
       'winner.clan.badgeId', 'loser.tag', 'loser.startingTrophies',
       'loser.trophyChange', 'loser.crowns', 'loser.kingTowerHitPoints',
       'loser.clan.tag', 'loser.clan.badgeId', 'loser.princessTowersHitPoints',
       'tournamentTag'])
df.columns

Index(['gameMode.id', 'average.startingTrophies', 'winner.card1.id',
       'winner.card1.level', 'winner.card2.id', 'winner.card2.level',
       'winner.card3.id', 'winner.card3.level', 'winner.card4.id',
       'winner.card4.level', 'winner.card5.id', 'winner.card5.level',
       'winner.card6.id', 'winner.card6.level', 'winner.card7.id',
       'winner.card7.level', 'winner.card8.id', 'winner.card8.level',
       'winner.cards.list', 'winner.totalcard.level', 'winner.troop.count',
       'winner.structure.count', 'winner.spell.count', 'winner.common.count',
       'winner.rare.count', 'winner.epic.count', 'winner.legendary.count',
       'winner.elixir.average', 'loser.card1.id', 'loser.card1.level',
       'loser.card2.id', 'loser.card2.level', 'loser.card3.id',
       'loser.card3.level', 'loser.card4.id', 'loser.card4.level',
       'loser.card5.id', 'loser.card5.level', 'loser.card6.id',
       'loser.card6.level', 'loser.card7.id', 'loser.card7.level',
       'loser.card8.id', 'loser.card8.level', 'loser.cards.list',
       'loser.totalcard.level', 'loser.troop.count', 'loser.structure.count',
       'loser.spell.count', 'loser.common.count', 'loser.rare.count',
       'loser.epic.count', 'loser.legendary.count', 'loser.elixir.average'],
      dtype='object')

In [27]:
df.head()

,gameMode.id,average.startingTrophies,winner.card1.id,winner.card1.level,winner.card2.id,winner.card2.level,winner.card3.id,winner.card3.level,winner.card4.id,winner.card4.level,...,loser.cards.list,loser.totalcard.level,loser.troop.count,loser.structure.count,loser.spell.count,loser.common.count,loser.rare.count,loser.epic.count,loser.legendary.count,loser.elixir.average
0,72000006.0,5363.0,26000008,13,26000022,13,28000001,13,26000004,13,...,"[26000000, 26000015, 26000023, 27000004, 28000...",104,3,1,4,1,1,4,2,3.500
1,72000006.0,5407.0,26000056,13,28000011,12,27000003,12,26000010,12,...,"[26000023, 26000027, 26000037, 26000046, 26000...",104,6,1,1,0,1,2,5,4.250
2,72000006.0,5741.0,26000044,13,26000059,13,26000010,13,26000061,13,...,"[26000022, 26000027, 26000028, 26000041, 26000...",104,7,0,1,4,2,1,1,4.125
3,72000006.0,4307.0,28000004,11,28000000,9,26000041,11,26000016,10,...,"[26000012, 26000027, 26000031, 26000033, 26000...",80,6,1,1,2,1,2,3,3.750
4,72000006.0,5776.5,28000011,13,26000021,13,26000014,13,26000038,13,...,"[26000010, 26000011, 26000021, 26000037, 26000...",104,5,1,2,2,4,0,2,3.250

In [28]:
len(df) #2823527
df2 = df.loc[df['average.startingTrophies'] >= 5500] #filter dataframe by skill, indicated by trophy count 5500
len(df2)

370033

In [29]:
df2 = df2[['loser.cards.list','winner.cards.list']].copy()
df2 = df2.reset_index(drop=True)
df2

,loser.cards.list,winner.cards.list
0,"[26000022, 26000027, 26000028, 26000041, 26000...","[26000010, 26000042, 26000044, 26000055, 26000..."
1,"[26000010, 26000011, 26000021, 26000037, 26000...","[26000010, 26000014, 26000021, 26000030, 26000..."
2,"[26000003, 26000016, 26000027, 26000037, 26000...","[26000001, 26000046, 26000047, 26000057, 26000..."
3,"[26000021, 26000027, 26000031, 26000037, 26000...","[26000004, 26000036, 26000042, 26000046, 26000..."
4,"[26000037, 26000042, 26000046, 26000055, 26000...","[26000006, 26000023, 26000037, 27000012, 28000..."
...,...,...
370028,"[26000013, 26000028, 26000038, 26000044, 26000...","[26000027, 26000044, 26000059, 26000062, 27000..."
370029,"[26000009, 26000013, 26000015, 26000035, 26000...","[26000000, 26000010, 26000019, 26000064, 27000..."
370030,"[26000008, 26000009, 26000041, 26000048, 26000...","[26000009, 26000015, 26000023, 26000048, 27000..."
370031,"[26000004, 26000005, 26000015, 26000036, 26000...","[26000009, 26000015, 26000023, 26000048, 27000..."
370032,"[26000000, 26000010, 26000026, 26000040, 26000...","[26000009, 26000015, 26000018, 26000039, 26000..."

In [76]:
df_cards = pd.read_csv('cardmaster.csv')
df_cards = df_cards.rename(columns = {'team.card1.id' : 'id' , 'team.card1.name' : 'name'})

In [77]:
df_cards['type'] = "Troop"
df_cards['type'][71:83] = "Building"
df_cards['type'][83:] = "Spell"
with pd.option_context('display.max_rows', None, 'display.max_columns', None):  # more options can be specified also
    print(df_cards)

           id              name      type
0    26000000            Knight     Troop
1    26000001           Archers     Troop
2    26000002           Goblins     Troop
3    26000003             Giant     Troop
4    26000004         P.E.K.K.A     Troop
5    26000005           Minions     Troop
6    26000006           Balloon     Troop
7    26000007             Witch     Troop
8    26000008        Barbarians     Troop
9    26000009             Golem     Troop
10   26000010         Skeletons     Troop
11   26000011          Valkyrie     Troop
12   26000012     Skeleton Army     Troop
13   26000013            Bomber     Troop
14   26000014         Musketeer     Troop
15   26000015       Baby Dragon     Troop
16   26000016            Prince     Troop
17   26000017            Wizard     Troop
18   26000018    Mini P.E.K.K.A     Troop
19   26000019     Spear Goblins     Troop
20   26000020    Giant Skeleton     Troop
21   26000021         Hog Rider     Troop
22   26000022      Minion Horde     Troop
23   26000023        Ice Wizard     Troop
24   26000024       Royal Giant     Troop
25   26000025            Guards     Troop
26   26000026          Princess     Troop
27   26000027       Dark Prince     Troop
28   26000028  Three Musketeers     Troop
29   26000029        Lava Hound     Troop
30   26000030        Ice Spirit     Troop
31   26000031      Fire Spirits     Troop
32   26000032             Miner     Troop
33   26000033            Sparky     Troop
34   26000034            Bowler     Troop
35   26000035        Lumberjack     Troop
36   26000036        Battle Ram     Troop
37   26000037    Inferno Dragon     Troop
38   26000038         Ice Golem     Troop
39   26000039       Mega Minion     Troop
40   26000040       Dart Goblin     Troop
41   26000041       Goblin Gang     Troop
42   26000042    Electro Wizard     Troop
43   26000043  Elite Barbarians     Troop
44   26000044            Hunter     Troop
45   26000045       Executioner     Troop
46   26000046            Bandit     Troop
47   26000047    Royal Recruits     Troop
48   26000048       Night Witch     Troop
49   26000049              Bats     Troop
50   26000050       Royal Ghost     Troop
51   26000051         Ram Rider     Troop
52   26000052           Zappies     Troop
53   26000053           Rascals     Troop
54   26000054       Cannon Cart     Troop
55   26000055       Mega Knight     Troop
56   26000056   Skeleton Barrel     Troop
57   26000057    Flying Machine     Troop
58   26000058     Wall Breakers     Troop
59   26000059        Royal Hogs     Troop
60   26000060      Goblin Giant     Troop
61   26000061         Fisherman     Troop
62   26000062      Magic Archer     Troop
63   26000063    Electro Dragon     Troop
64   26000064       Firecracker     Troop
65   26000067      Elixir Golem     Troop
66   26000068     Battle Healer     Troop
67   26000080  Skeleton Dragons     Troop
68   26000083      Mother Witch     Troop
69   26000084    Electro Spirit     Troop
70   26000085     Electro Giant     Troop
71   27000000            Cannon  Building
72   27000001        Goblin Hut  Building
73   27000002            Mortar  Building
74   27000003     Inferno Tower  Building
75   27000004        Bomb Tower  Building
76   27000005     Barbarian Hut  Building
77   27000006             Tesla  Building
78   27000007  Elixir Collector  Building
79   27000008             X-Bow  Building
80   27000009         Tombstone  Building
81   27000010           Furnace  Building
82   27000012       Goblin Cage  Building
83   28000000          Fireball     Spell
84   28000001            Arrows     Spell
85   28000002              Rage     Spell
86   28000003            Rocket     Spell
87   28000004     Goblin Barrel     Spell
88   28000005            Freeze     Spell
89   28000006            Mirror     Spell
90   28000007         Lightning     Spell
91   28000008               Zap     Spell
92   28000009            Poison     Spell
93   28000010         Graveyard     Spell
94   28000011           The Log     Spell
95   28000012           Tornado     Spell
96   28000013             Clone     Spell
97   28000014        Earthquake     Spell
98   28000015  Barbarian Barrel     Spell
99   28000016       Heal Spirit     Spell
100  28000017    Giant Snowball     Spell
101  28000018    Royal Delivery     Spell

/var/folders/sl/pz8cryzs76nccmdlf5tymgnm0000gn/T/ipykernel_2184/1847011758.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_cards['type'][71:83] = "Building"
/var/folders/sl/pz8cryzs76nccmdlf5tymgnm0000gn/T/ipykernel_2184/1847011758.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_cards['type'][83:] = "Spell"

In [90]:
#create dictionary to translate (also doing it for troop now)
card_dict = {}
for i in range(len(df_cards)):
    card_dict[df_cards['id'][i]] = df_cards['name'][i]
    
type_dict = {}
for i in range(len(df_cards)):
    type_dict[df_cards['name'][i]] = df_cards['type'][i]

In [32]:
type(df2['loser.cards.list'][0]) #string representation of list in each row
example = ast.literal_eval(df2['loser.cards.list'][0]) #convert string rep into actual list
example

[26000022,
 26000027,
 26000028,
 26000041,
 26000046,
 26000049,
 26000059,
 28000008]

In [33]:
#translate the list from id to human-readable card names
result = []
for i in example:
    result.append(card_dict[i])
result.sort()
result

['Bandit',
 'Bats',
 'Dark Prince',
 'Goblin Gang',
 'Minion Horde',
 'Royal Hogs',
 'Three Musketeers',
 'Zap']

In [89]:
#combine both previous steps into one function
def translator(row):
    temp = ast.literal_eval(row)
    result = []
    for i in temp:
        result.append(card_dict[i])
    result.sort()
    return result

In [35]:
#func to help me debug using apply on each column
def printer(x):
    print(type(x))
    print(x)

In [36]:
new_df = df2['loser.cards.list'].apply(translator)
new_df2 = df2['winner.cards.list'].apply(translator)

In [37]:
final_df = pd.concat([new_df,new_df2], axis=1)
final_df = final_df.rename(columns = {'loser.cards.list': 'loser', 'winner.cards.list':'winner'},)
final_df

,loser,winner
0,"[Bandit, Bats, Dark Prince, Goblin Gang, Minio...","[Barbarian Barrel, Electro Wizard, Fisherman, ..."
1,"[Bomb Tower, Fireball, Firecracker, Hog Rider,...","[Cannon, Fireball, Hog Rider, Ice Golem, Ice S..."
2,"[Dark Prince, Electro Wizard, Fireball, Giant,...","[Archers, Bandit, Earthquake, Flying Machine, ..."
3,"[Arrows, Bats, Dark Prince, Fire Spirits, Hog ...","[Bandit, Battle Ram, Electro Wizard, Magic Arc..."
4,"[Arrows, Bandit, Barbarian Barrel, Electro Wiz...","[Balloon, Barbarian Barrel, Goblin Cage, Ice W..."
...,...,...
370028,"[Bandit, Bomber, Elixir Collector, Hunter, Ice...","[Barbarian Barrel, Dark Prince, Earthquake, Go..."
370029,"[Baby Dragon, Bomber, Golem, Lightning, Lumber...","[Earthquake, Firecracker, Knight, Mortar, Skel..."
370030,"[Arrows, Barbarians, Clone, Flying Machine, Go...","[Baby Dragon, Barbarian Barrel, Goblin Cage, G..."
370031,"[Baby Dragon, Barbarian Barrel, Battle Ram, El...","[Baby Dragon, Barbarian Barrel, Goblin Cage, G..."
370032,"[Bomb Tower, Dart Goblin, Goblin Barrel, Knigh...","[Arrows, Baby Dragon, Barbarian Barrel, Golem,..."

In [38]:
#final_df[final_df['loser'].apply(lambda x: 'Arrows' in x)] 
#this line of code is for finding one card from the losers' cards as opposed to searching for a deck

In [47]:
#use this to search for games with this deck
deck = ['Skeletons','Cannon','Ice Spirit','Ice Golem','Hog Rider','Fireball','Musketeer','The Log']
deck.sort()

#search for losers who lost using this specific deck
temp_list = list(final_df['loser'])
deck_losers_indices = []

#these are all the games where deck lost
for i in range(len(temp_list)):
    if temp_list[i] == deck:
        deck_losers_indices.append(i)

In [48]:
#these are all the games where hog2.6 lost, 'winners' is the decks that won against hog 2.6
winners = []
total_winner_cards = []
for i in deck_losers_indices:
    winners.append(final_df['winner'][i])
    for k in final_df['winner'][i]:
        total_winner_cards.append(k)

In [49]:
counter = dict.fromkeys(df_cards['name'], 0)
for i in total_winner_cards:
    counter[i] += 1
{k: v for k, v in sorted(counter.items(), key=lambda item: item[1])}

{'Three Musketeers': 43,
 'Mirror': 47,
 'Electro Giant': 49,
 'Fire Spirits': 50,
 'Elite Barbarians': 65,
 'Mother Witch': 66,
 'Goblins': 82,
 'Rascals': 85,
 'Royal Delivery': 90,
 'Elixir Collector': 93,
 'Barbarian Hut': 100,
 'Battle Healer': 101,
 'Witch': 106,
 'Elixir Golem': 108,
 'Heal Spirit': 108,
 'Royal Recruits': 118,
 'Furnace': 123,
 'Cannon': 138,
 'Goblin Giant': 140,
 'Ram Rider': 141,
 'Guards': 166,
 'Mortar': 167,
 'Electro Spirit': 171,
 'Royal Hogs': 180,
 'Clone': 187,
 'Wall Breakers': 188,
 'Goblin Hut': 204,
 'Tombstone': 204,
 'Executioner': 206,
 'Wizard': 210,
 'Zappies': 216,
 'Minion Horde': 225,
 'Bowler': 232,
 'Rage': 234,
 'Firecracker': 236,
 'Giant Skeleton': 241,
 'Sparky': 241,
 'Bomber': 254,
 'Dart Goblin': 263,
 'X-Bow': 264,
 'Electro Dragon': 272,
 'Battle Ram': 291,
 'Fisherman': 296,
 'Flying Machine': 300,
 'Royal Ghost': 302,
 'Cannon Cart': 327,
 'Giant': 346,
 'Royal Giant': 357,
 'Magic Archer': 358,
 'Freeze': 359,
 'Archers': 367,
 'Earthquake': 372,
 'Ice Golem': 393,
 'Inferno Tower': 415,
 'Spear Goblins': 420,
 'Prince': 438,
 'Minions': 452,
 'Skeleton Barrel': 478,
 'Skeleton Dragons': 493,
 'Goblin Cage': 498,
 'Barbarians': 516,
 'Bandit': 525,
 'Mega Knight': 540,
 'Giant Snowball': 550,
 'Lava Hound': 554,
 'Tesla': 554,
 'Princess': 572,
 'Valkyrie': 581,
 'P.E.K.K.A': 584,
 'Rocket': 605,
 'Hunter': 617,
 'Ice Spirit': 648,
 'Hog Rider': 664,
 'Goblin Barrel': 664,
 'Mini P.E.K.K.A': 668,
 'Dark Prince': 694,
 'Skeleton Army': 703,
 'Lumberjack': 703,
 'Bomb Tower': 729,
 'Graveyard': 765,
 'Musketeer': 767,
 'Inferno Dragon': 790,
 'Goblin Gang': 811,
 'Ice Wizard': 838,
 'Lightning': 910,
 'Poison': 933,
 'Golem': 939,
 'Bats': 951,
 'Electro Wizard': 953,
 'Night Witch': 962,
 'Mega Minion': 980,
 'Miner': 1106,
 'Skeletons': 1124,
 'Balloon': 1149,
 'Arrows': 1234,
 'Fireball': 1372,
 'Knight': 1645,
 'Baby Dragon': 1655,
 'Barbarian Barrel': 1666,
 'Zap': 1691,
 'The Log': 1831,
 'Tornado': 1845}

<img src="Hog26Viz.jpg">

In [53]:
#saving hogrider file to csv for visualization

# load csv module
import csv

# define a dictionary with key value pairs
counter

# open file for writing, "w" is writing
w = csv.writer(open("hog26.csv", "w"))

# loop over dictionary keys and values
for key, val in counter.items():
    # write every key and value to file
    w.writerow([key, val])

In [54]:
#side project: seeing which cards are way too strong in the meta by counting occurences 
#of cards from the winner list

final_df['winner']
strong_meta = []
for i in range(len(final_df['winner'])):
    for k in final_df['winner'][i]:
        strong_meta.append(k)

        
meta_counter = dict.fromkeys(df_cards['name'], 0)
for i in strong_meta:
    meta_counter[i] += 1
#{k: v for k, v in sorted(meta_counter.items(), key=lambda item: item[1])}

In [58]:
#deriving win rate % to check which cards are performing well in the meta and which cards need balancing
win_rates = {}
for key, val in meta_counter.items():
    win_rates[key] = (val / 370033) * 100 #this is the total number of games from the previous dataframe
    
win_rates

{'Knight': 23.185769917818142,
 'Archers': 5.074952774482276,
 'Goblins': 1.3142071112576446,
 'Giant': 5.517345750243898,
 'P.E.K.K.A': 10.536627814276024,
 'Minions': 6.584007372315442,
 'Balloon': 16.706618058389385,
 'Witch': 1.7144416849308035,
 'Barbarians': 8.016852550988695,
 'Golem': 12.74210678507052,
 'Skeletons': 14.998121789137725,
 'Valkyrie': 8.942715919931466,
 'Skeleton Army': 10.483389319330978,
 'Bomber': 3.8988414546810692,
 'Musketeer': 11.143330459715756,
 'Baby Dragon': 22.340439906711023,
 'Prince': 7.639588901530405,
 'Wizard': 3.56589817664911,
 'Mini P.E.K.K.A': 10.589325816886602,
 'Spear Goblins': 7.649317763550818,
 'Giant Skeleton': 4.6433696454100035,
 'Hog Rider': 9.83560925647172,
 'Minion Horde': 3.918028932554664,
 'Ice Wizard': 10.02234935803023,
 'Royal Giant': 5.264395337713123,
 'Guards': 2.0398180702802184,
 'Princess': 9.02919469344626,
 'Dark Prince': 11.55410463391103,
 'Three Musketeers': 1.0307188818294586,
 'Lava Hound': 7.570676128885802,
 'Ice Spirit': 9.266200582110244,
 'Fire Spirits': 1.0623376833958051,
 'Miner': 16.014247377936563,
 'Sparky': 4.080446879062138,
 'Bowler': 2.6232795453378484,
 'Lumberjack': 10.003702372491102,
 'Battle Ram': 6.2548475406247555,
 'Inferno Dragon': 12.980463904570675,
 'Ice Golem': 6.809933168122844,
 'Mega Minion': 14.603021892642007,
 'Dart Goblin': 4.822813100453203,
 'Goblin Gang': 12.421865076898547,
 'Electro Wizard': 15.862369031951204,
 'Elite Barbarians': 1.2709677245002473,
 'Hunter': 11.007126391429955,
 'Executioner': 3.024324857512708,
 'Bandit': 10.192334197220248,
 'Royal Recruits': 2.605443298300422,
 'Night Witch': 13.319893090616242,
 'Bats': 14.79651814838136,
 'Royal Ghost': 6.010004513110992,
 'Ram Rider': 2.532747079314548,
 'Zappies': 4.566079241581156,
 'Rascals': 1.7557893485175649,
 'Cannon Cart': 5.619498801458248,
 'Mega Knight': 8.128734464223461,
 'Skeleton Barrel': 8.66220039834285,
 'Flying Machine': 5.02820018755084,
 'Wall Breakers': 3.1289101242321626,
 'Royal Hogs': 3.8780324998040716,
 'Goblin Giant': 2.264662881418684,
 'Fisherman': 4.406634002913254,
 'Magic Archer': 6.849659354706201,
 'Electro Dragon': 4.946856091213486,
 'Firecracker': 4.235568179054301,
 'Elixir Golem': 2.1284588131328825,
 'Battle Healer': 2.0327916699321413,
 'Skeleton Dragons': 6.970729637626914,
 'Mother Witch': 1.0458526671945476,
 'Electro Spirit': 3.387535706274846,
 'Electro Giant': 0.7483116370702073,
 'Cannon': 2.014955422894715,
 'Goblin Hut': 3.34078311934341,
 'Mortar': 3.5456297141065796,
 'Inferno Tower': 6.196204122335034,
 'Bomb Tower': 9.503206470774227,
 'Barbarian Hut': 1.661203189985758,
 'Tesla': 7.023427640237492,
 'Elixir Collector': 1.7525463945107598,
 'X-Bow': 3.3361889345004365,
 'Tombstone': 2.788670199684893,
 'Furnace': 2.1111630584299235,
 'Goblin Cage': 6.58887180332565,
 'Fireball': 22.72310847951399,
 'Arrows': 18.758056713860654,
 'Rage': 3.7442606470233737,
 'Rocket': 8.914880564706392,
 'Goblin Barrel': 10.554734307480684,
 'Freeze': 4.497706961271022,
 'Mirror': 0.8158731788786405,
 'Lightning': 12.202425189104755,
 'Zap': 28.489891442114622,
 'Poison': 15.063251115441057,
 'Graveyard': 9.311331692038276,
 'The Log': 28.049930681858104,
 'Tornado': 24.00164309669678,
 'Clone': 2.545718895341767,
 'Earthquake': 5.463837009131618,
 'Barbarian Barrel': 24.9150751419468,
 'Heal Spirit': 1.7771387957290294,
 'Giant Snowball': 7.788494539676191,
 'Royal Delivery': 1.6182340493955945}

<img src="WinRatesViz.jpg"/>

In [92]:
#saving win_rates file to csv for visualization

# load csv module
import csv

# define a dictionary with key value pairs
win_rates

# open file for writing, "w" is writing
w = csv.writer(open("win_rates.csv", "w"))

# loop over dictionary keys and values
for key, val in win_rates.items():
    # write every key and value to file
    w.writerow([key, val])